"""Add LocalAsset for tracking downloaded assets

Revision ID: 2abace98a31c
Revises: d3f8a1c9b2e4
Create Date: 2026-09-17 11:20:37.250525

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2abace98a31c"
down_revision: str | Sequence[str] | None = "d3f8a1c9b2e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "local_assets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("notebook_id", sa.String(), nullable=False),
        sa.Column("asset_id", sa.String(), nullable=False),
        sa.Column("asset_type", sa.String(), nullable=False),
        sa.Column("local_path", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_local_assets_asset_id"), "local_assets", ["asset_id"], unique=True)
    op.create_index(
        op.f("ix_local_assets_notebook_id"), "local_assets", ["notebook_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_local_assets_notebook_id"), table_name="local_assets")
    op.drop_index(op.f("ix_local_assets_asset_id"), table_name="local_assets")
    op.drop_table("local_assets")
    # ### end Alembic commands ###
