"""verify

Revision ID: acc6b9b32ee1
Revises: 226e0b882afd
Create Date: 2026-09-17 04:45:08.751596

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'acc6b9b32ee1'
down_revision: str | Sequence[str] | None = '226e0b882afd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
